### ISSUE TITLE
Feature Request: Allow "READ_CLIPBOARD" permission to "Foreground" apps only.

### ISSUE THREAD

**Issue by ashjas** [RikkaApps/App-Ops-issue-tracker#17]
Feature request:

"Read Clipboard" Permission is only "Allowed" to apps that are in foreground only.
Dont make this default, just an option for user, if he intends to enable such a setting.
This will let users mitigate the famous android clipboard security issue, where any app can listen to contents of the clipboard, and possibly leak private information.

Or to be more generic,
Allow selected permissions to an app only when it comes in foreground.

**Comment by haruue** [comment]
App Ops will require more permissions (to known which application is in foreground) and keep a process in the background (because there is nothing that can launch App Ops when the foreground-background status of other applications switched).

So this feature won't be implemented. At least won't in current version of Android.

Thanks for using App Ops.
