### ISSUE TITLE
System plugin method still supported?

### ISSUE THREAD

**Issue by truthbeliever** [RikkaApps/App-Ops-issue-tracker#18]
Hello,

I installed xiaomi.eu 9.5 for Xiaomi Redmi 3s - land together with the app ops system plugin via TWRP.
now after having booted up and installing the latest AppOps, it does not detect the plugin and does not suggest the plugin method, only root and Shizuku method. 

Is the plugin method still supported?
Thank you

**Comment by haruue** [comment]
If system plugin is not installed, the **System Plugin** option won't show on setup wizard. Because some users select this option before they know what they are doing, and then complain that the application does not work, or just uninstall and vote it 1 star. It is really annoying.

To use system plugin mode, Please choose **ROOT** mode in the setup wizard. Then go to **Settings** - **Working mode and behavior**, where you can find the **System plugin** option.

Thanks for using App Ops.

**Comment by haruue** [comment]
As this question is solved, I will close it now. Feel free to reopen it if you have further problem.
