### ISSUE TITLE
Android Pie compatibility

### ISSUE THREAD

**Issue by yochananmarqos** [RikkaApps/App-Ops-issue-tracker#21]
I'm not able to change permissions on Android Pie on my Google Pixel. It was working fine on Oreo 8.1. I'm using the Magisk module. 

**EDIT**: The module template needed to be updated to v17000. I updated it and emailed it to to the developer. ~~For now you can download it from my Drive here.~~

**Comment by Koncrete** [comment]
TY for the module, I installed it then rebooted and the helper app show up but app ops cannot see it? Not sure how to fix

**Comment by yochananmarqos** [comment]
@Koncrete I'm not sure what you mean. Does the app list populate with the System Plugin selected in Settings > Working Mode? Also tapping Install System Plugin (Require Root) should show a green checkmark and "Plugin activated (version 6)". It's actually version 8, not sure why it shows 6.

I'm using App Ops 2.41.r165.6a20010 and Magisk 17.2 beta, though it also will work with 17.1 stable.

**Comment by Koncrete** [comment]
I'm using beta as well on pie, essential phone, the module flashed fine and the helper app is listed in applications and has permissions.  But in app ops it still want me to install it even though app ops has root perm. When I tap install app it launches to here to install the older versions, that's how I found your post

**Comment by yochananmarqos** [comment]
@Koncrete Try switching to ROOT mode, let the app list populate, exit the app then go back and switch it to System plugin..

**Comment by Koncrete** [comment]
I figured an odd work around... I put it in system plugin mode then went to lab and ran test. Went back to install plugin and it's checked now.

**Comment by Koncrete** [comment]
TY for helping though!

**Comment by RikkaW** [comment]
I don't think system plugin can work on Android P, since set appops need a new permission added from P ([MANAGE_APP_OPS_MODES](https://github.com/aosp-mirror/platform_frameworks_base/blob/pie-release/core/res/AndroidManifest.xml#L2625-L2626) ([where it is checked](https://github.com/aosp-mirror/platform_frameworks_base/blob/pie-release/services/core/java/com/android/server/AppOpsService.java#L968-L988))) and this permission seems can't be granted to a privileged app (apps in `/system/priv-app`). (The plugin can "work" on Android P but only list apps and appops settings not set appops settings, once try to set, an error will occur)

**Comment by yochananmarqos** [comment]
@RikkaW You're right, it can't set permissions and generates a stacktrace. I switched back to root mode.
